import { decodeJWT } from '../Auth';
import { search } from '.';

const pat =
    'ew0KICAiJGlkIjogbnVsbCwNCiAgIiR0eXBlIjogIlN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkRpY3Rpb25hcnlgMltbU3lzdGVtLlN0cmluZywgU3lzdGVtLlByaXZhdGUuQ29yZUxpYl0sW1N5c3RlbS5PYmplY3QsIFN5c3RlbS5Qcml2YXRlLkNvcmVMaWJdXSwgU3lzdGVtLlByaXZhdGUuQ29yZUxpYiIsDQogICJ0eXAiOiAiSldUIiwNCiAgImFsZyI6ICJIUzI1NiINCn0.ew0KICAiJGlkIjogbnVsbCwNCiAgIiR0eXBlIjogIkRhdGFHYWxheHkuQ29yZS5EYXRhLk1lc3NhZ2VTZWN1cml0eS5QZXJzb25hbEFjY2Vzc1Rva2VuUGF5bG9hZCwgRGF0YUdhbGF4eS5Db3JlLkRhdGEiLA0KICAiZGdhcGkiOiAiaHR0cHM6Ly9kZXZuZXh0LmRhdGFnYWxheHkuY29tL25leHRfc2VydmVyLyIsDQogICJwdWJhcGkiOiAiaHR0cHM6Ly9hcGl1YXQuZGF0YWdhbGF4eS5jb20vdjIiLA0KICAiY2lkIjogIjkzNDFlNGExLWY5MGYtNDY2Ny1hNWE4LWI0ODhmNGY4MmM0YyIsDQogICJ1aWQiOiAiNzcwNWIwYmMtYTkwZC00Yjg5LWFjODMtMTNhYTQzNDBmYTJlIiwNCiAgImdpdmVuX25hbWUiOiAiUm9tYWluIiwNCiAgImZhbWlseV9uYW1lIjogIlNpbW9uIiwNCiAgImVtYWlsIjogInJvbWFpbi5zaW1vbkB0aGV0cmliZS5pbyIsDQogICJzdWIiOiAicm9tYWluLnNpbW9uQHRoZXRyaWJlLmlvIiwNCiAgImlhdCI6ICIxNjI1NzQ2MjUzIiwNCiAgImV4cCI6ICIxNjU3MjgyMjUzIg0KfQ.ORZRLsbduuK7EqCNfFKjtyqpHU0gZjEtSVJKVu2XcDQ';

test('Search with query string "test" from API', async () => {
    const decodedPat = decodeJWT(pat);
    const searchResult = await search(decodedPat.pubapi, 'test');
    expect(searchResult.total).toBeGreaterThan(0);
});
