# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

variables: 
  NODE_VERSION: '14.17.1'
  PNPM_CACHE_FOLDER: ~/.pnpm-store


stages:
- stage: Build
  jobs:
  - job: InstallDependencies
    steps:
    - task: NodeTool@0
      displayName: 'Use Node $(NODE_VERSION)'
      inputs:
        versionSpec: '$(NODE_VERSION)'
    - task: Cache@2
      displayName: Cache PNPM packages
      inputs:
        key: '"node common/scripts/install-run-rush.js install" | "$(Agent.OS)" | common/config/rush/pnpm-lock.yaml'
        restoreKeys: |
          node common/scripts/install-run-rush.js install | "$(Agent.OS)"
        path: $(PNPM_CACHE_FOLDER)
    - script: 'node common/scripts/install-run-rush.js change --verify'
      displayName: 'Verify Change Logs'
    - script: 'node common/scripts/install-run-rush.js install'
      displayName: 'Rush Install'
    - script: 'node common/scripts/install-run-rush.js rebuild --verbose'
      displayName: 'Rush Rebuild'
    - script: 'node common/scripts/install-run-rush.js lint'
      displayName: 'Rush Lint'
